Resources:

  AppointmentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: apptId
          AttributeType: S
        - AttributeName: insureId
          AttributeType: S
      KeySchema:
        - AttributeName: apptId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: InsureIndex
          KeySchema:
            - AttributeName: insureId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:service}-appt-table
