service: reto-back

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: 
            - !GetAtt EventBus.Arn
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [AppointmentTable, Arn]
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - Fn::GetAtt: [PEAppointmentTopic, Arn]
            - Fn::GetAtt: [CLAppointmentTopic, Arn]
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - Fn::GetAtt: [SQS_PE, Arn]
            - Fn::GetAtt: [SQS_CL, Arn]
            - Fn::GetAtt: [SQS, Arn]
        - Effect: Allow
          Action:
            - rds-db:connect
          Resource:
            - "TO BE REPLACED"
            
  environment:
    APPT_TABLE: ${self:service}-appt-table
    PE_TOPIC_ARN: !GetAtt PEAppointmentTopic.Arn
    CL_TOPIC_ARN: !GetAtt CLAppointmentTopic.Arn

functions:
functions:
  - ${file(cloudformation/functions.yml)}

resources:
  - ${file(cloudformation/dynamodb.yml)}
  - ${file(cloudformation/cloudfront.yml)}
  - ${file(cloudformation/resources.yml)}
  - ${file(cloudformation/opensearch.yml)}
